security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login: ~
            entry_point: form_login
            login_throttling:
                max_attempts: 3
                interval: '15 minutes'
            logout:
                path: logout
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
